#!/usr/bin/env python3
"""Apply human review decisions to ifind_chain_panel.

The input is the CSV generated by build_chain_panel_review_sample.py. Only rows
with review_status=verified are promoted to manual_verified=true by default.
Rows marked rejected/needs_research are logged but do not mutate the panel.
"""

from __future__ import annotations

import argparse
import csv
import json
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

import duckdb

ROOT = Path(__file__).resolve().parents[1]
DEFAULT_DB = ROOT / "outputs" / "industry_chain" / "industry_chain_evidence.duckdb"
DEFAULT_LOG = ROOT / "outputs" / "industry_chain" / "chain_panel_review_log.jsonl"

VALID_STATUSES = {"verified", "rejected", "needs_research"}


def _clean(value: Any) -> str:
    return str(value or "").strip()


def load_review_csv(path: Path) -> list[dict[str, str]]:
    with path.open("r", encoding="utf-8-sig", newline="") as fh:
        return [dict(row) for row in csv.DictReader(fh)]


def validate_rows(rows: list[dict[str, str]]) -> list[str]:
    errors: list[str] = []
    required = {"chain_id", "node_id", "stock_code", "as_of_date", "review_status"}
    for i, row in enumerate(rows, start=2):
        missing = [col for col in required if col not in row]
        if missing:
            errors.append(f"row {i}: missing columns {missing}")
            continue
        status = _clean(row.get("review_status"))
        if not status:
            continue
        if status not in VALID_STATUSES:
            errors.append(f"row {i}: invalid review_status={status!r}")
        for col in ["chain_id", "node_id", "stock_code", "as_of_date"]:
            if not _clean(row.get(col)):
                errors.append(f"row {i}: empty required value {col}")
    return errors


def apply_review(
    csv_path: Path,
    db_path: Path = DEFAULT_DB,
    log_path: Path = DEFAULT_LOG,
    reviewer: str | None = None,
    dry_run: bool = False,
    apply_rejections: bool = False,
) -> dict[str, Any]:
    if not csv_path.exists():
        return {"ok": False, "error": f"Review CSV not found: {csv_path}"}
    if not db_path.exists():
        return {"ok": False, "error": f"Database not found: {db_path}"}

    rows = load_review_csv(csv_path)
    errors = validate_rows(rows)
    if errors:
        return {"ok": False, "error": "Invalid review CSV", "details": errors[:20]}

    reviewed_at = datetime.now(timezone.utc).isoformat()
    decisions = []
    for row in rows:
        status = _clean(row.get("review_status"))
        if not status:
            continue
        decisions.append(
            {
                "chain_id": _clean(row.get("chain_id")),
                "node_id": _clean(row.get("node_id")),
                "stock_code": _clean(row.get("stock_code")),
                "as_of_date": _clean(row.get("as_of_date")),
                "source_type": _clean(row.get("source_type")),
                "review_status": status,
                "reviewed_node_id": _clean(row.get("reviewed_node_id")) or _clean(row.get("node_id")),
                "reviewer_note": _clean(row.get("reviewer_note")),
                "reviewer": reviewer or _clean(row.get("reviewer")),
                "reviewed_at": _clean(row.get("reviewed_at")) or reviewed_at,
            }
        )

    verified = [d for d in decisions if d["review_status"] == "verified"]
    verified_without_node_change = [d for d in verified if d["reviewed_node_id"] == d["node_id"]]
    verified_with_node_change = [d for d in verified if d["reviewed_node_id"] != d["node_id"]]
    rejections = [d for d in decisions if d["review_status"] == "rejected"]

    changed = 0
    matched_verified = 0
    if not dry_run and decisions:
        con = duckdb.connect(str(db_path))
        try:
            for decision in verified_without_node_change:
                exists = con.execute(
                    """
                    SELECT COUNT(*)
                    FROM ifind_chain_panel
                    WHERE chain_id = ?
                      AND node_id = ?
                      AND stock_code = ?
                      AND as_of_date = ?
                    """,
                    (
                        decision["chain_id"],
                        decision["node_id"],
                        decision["stock_code"],
                        decision["as_of_date"],
                    ),
                ).fetchone()[0]
                if exists:
                    matched_verified += 1
                    con.execute(
                        """
                        UPDATE ifind_chain_panel
                        SET manual_verified = true,
                            updated_at = ?
                        WHERE chain_id = ?
                          AND node_id = ?
                          AND stock_code = ?
                          AND as_of_date = ?
                        """,
                        (
                            reviewed_at,
                            decision["chain_id"],
                            decision["node_id"],
                            decision["stock_code"],
                            decision["as_of_date"],
                        ),
                    )
                    changed += 1

            if apply_rejections:
                for decision in rejections:
                    con.execute(
                        """
                        UPDATE ifind_chain_panel
                        SET manual_verified = false,
                            updated_at = ?
                        WHERE chain_id = ?
                          AND node_id = ?
                          AND stock_code = ?
                          AND as_of_date = ?
                        """,
                        (
                            reviewed_at,
                            decision["chain_id"],
                            decision["node_id"],
                            decision["stock_code"],
                            decision["as_of_date"],
                        ),
                    )
        finally:
            con.close()

        log_path.parent.mkdir(parents=True, exist_ok=True)
        with log_path.open("a", encoding="utf-8") as fh:
            for decision in decisions:
                fh.write(json.dumps(decision, ensure_ascii=False) + "\n")
    else:
        matched_verified = len(verified_without_node_change)

    return {
        "ok": True,
        "dry_run": dry_run,
        "review_csv": str(csv_path),
        "decisions": len(decisions),
        "verified_decisions": len(verified),
        "verified_node_corrections_skipped": len(verified_with_node_change),
        "matched_verified": matched_verified,
        "rows_changed": changed,
        "rejected_decisions": len(rejections),
        "needs_research_decisions": sum(1 for d in decisions if d["review_status"] == "needs_research"),
        "log_path": str(log_path),
    }


def main() -> int:
    parser = argparse.ArgumentParser(description="Apply reviewed ifind_chain_panel sample rows.")
    parser.add_argument("csv_path", help="CSV generated by build_chain_panel_review_sample.py")
    parser.add_argument("--db", default=str(DEFAULT_DB))
    parser.add_argument("--log", default=str(DEFAULT_LOG))
    parser.add_argument("--reviewer", help="Reviewer name to store in log")
    parser.add_argument("--dry-run", action="store_true")
    parser.add_argument("--apply-rejections", action="store_true", help="Also force rejected rows to manual_verified=false")
    args = parser.parse_args()

    result = apply_review(
        csv_path=Path(args.csv_path),
        db_path=Path(args.db),
        log_path=Path(args.log),
        reviewer=args.reviewer,
        dry_run=args.dry_run,
        apply_rejections=args.apply_rejections,
    )
    print(json.dumps(result, ensure_ascii=False, indent=2))
    return 0 if result.get("ok") else 1


if __name__ == "__main__":
    raise SystemExit(main())
